### ISSUE TITLE
S-6: MongoDB Database Schema Setup

### ISSUE THREAD

**Issue by desslinga** [wafffly/closetr#16] opened 2018-12-01 00:30 UTC
**Description** : Using the schema plan generated, implement the schema in the database. Populate the database with sample data which will be used for testing future API calls.

**Required**
- Implement schema onto database.
- Populate database with sample data.

**Development Estimates**
- Development: 2 hours.

**Comment by JoshuaConcon** [comment] 2019-01-06 01:33
Duplicate of S-12, closing

**Closed by JoshuaConcon** 2019-01-06 01:33 UTC
Labels: duplicate
