### ISSUE TITLE
S-8: Closetr API, Return All Clothing Articles

### ISSUE THREAD

**Issue by desslinga** [wafffly/closetr#19] opened 2018-12-02 00:19 UTC
**Description**: An API is required to return all clothing pieces in the database in a JSON format. The API must be connected to a route that the front-end can call.

**Required**
- Create API to return clothing articles in JSON format.
- Set up the API to a route (string).

**Development Estimates**
- Development: 5 hours.

**Comment by JoshuaConcon** [comment] 2019-01-06 01:32
Duplicate of S-12, closing

**Closed by JoshuaConcon** 2019-01-06 01:32 UTC
