### ISSUE TITLE
S-5: MongoDB Configuration

### ISSUE THREAD

**Issue by desslinga** [wafffly/closetr#15] opened 2018-12-01 00:28 UTC
**Description** : Configure a MongoDB database onto the back-end project (closetr-api), so that APIs can be made to communicate with the database.

**Required**
- MongoDB configuration with the back-end.
- Establish an architecture that enable DB connections with all future closetr APIs, using best practices.

**Development Estimates**
- Development: 6 hours.

**Comment by JoshuaConcon** [comment] 2019-01-06 01:34
Duplicate of S-12, closing

**Closed by JoshuaConcon** 2019-01-06 01:34 UTC
Labels: duplicate
